public class AngkaSial {
    public void cobaAngka(int angka) throws AngkaSialException{
        if (angka == 13){
            throw new AngkaSialException();
        }
        System.out.println(angka + " bukan angka sial");
    }
    
    public static void main(String[] args) {
        AngkaSial as = new AngkaSial();
        try {
            as.cobaAngka(10);
            as.cobaAngka(13);
            as.cobaAngka(12);
        } catch (AngkaSialException ase) {
            System.out.println(ase.getMessage());
            System.out.println("hati-hati memasukkan angka!");
        }
    }
}

//Ketika eksepsi terjadi pada angka 13, program langsung masuk ke catch 
//dan baris 12 tidak dieksekusi. 
//Namun baris 21 dalam catch tetap dieksekusi untuk menampilkan pesan kesalahan. 